"use client";
/* eslint-disable @next/next/no-html-link-for-pages, @next/next/no-location-assign-relative-destination */
import { useEffect, useState } from "react";

type Detail = { meeting: { title: string; started_at: string; ended_at: string | null; duration_seconds: number | null }; transcripts: { text: string; sequence: number }[]; summaries: { core: string; issues: string; speaking_point: string }[]; responses: { text: string }[]; note: { content: string } | null };

export default function MeetingDetail({ params }: { params: Promise<{ id: string }> }) {
  const [detail, setDetail] = useState<Detail | null>(null); const [error, setError] = useState(""); const [id, setId] = useState(""); const [editing, setEditing] = useState(false); const [title, setTitle] = useState(""); const [content, setContent] = useState(""); const [saveState, setSaveState] = useState<"idle" | "saving" | "saved" | "error">("idle");
  useEffect(() => { void params.then(({ id: value }) => { setId(value); void fetch(`/api/meetings/${value}`).then(async (r) => { const p = await r.json(); if (!r.ok) setError(p?.error?.message || "회의를 불러오지 못했습니다."); else { setDetail(p); setTitle(p.meeting.title); setContent(p.note?.content || ""); } }); }); }, [params]);
  const edit = () => { if (!detail) return; setTitle(detail.meeting.title); setContent(detail.note?.content || ""); setSaveState("idle"); setEditing(true); };
  const save = async () => { if (!title.trim() || !content.trim()) { setSaveState("error"); return; } setSaveState("saving"); try { const meetingResponse = await fetch(`/api/meetings/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title }) }); if (!meetingResponse.ok) throw new Error("회의 제목 저장에 실패했습니다."); const noteResponse = await fetch(`/api/meeting-notes/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title, content }) }); const payload = await noteResponse.json().catch(() => null); if (!noteResponse.ok) throw new Error(payload?.error?.message || "회의록 저장에 실패했습니다."); setDetail((current) => current ? { ...current, meeting: { ...current.meeting, title }, note: { content } } : current); setSaveState("saved"); setEditing(false); } catch { setSaveState("error"); } };
  const remove = async () => { if (!window.confirm("이 회의의 전사, 요약, 답변, 회의록이 모두 삭제됩니다. 계속하시겠습니까?")) return; const r = await fetch(`/api/meetings/${id}`, { method: "DELETE" }); if (r.ok) window.location.href = "/meetings"; };
  if (error) return <main className="archive-page"><a href="/meetings">← 지난 회의</a><p className="transcription-error">{error}</p></main>;
  if (!detail) return <main className="archive-page">불러오는 중...</main>;
  const last = detail.summaries[0];
  return <main className="archive-page"><a href="/meetings">← 지난 회의</a><p className="eyebrow">MEETING DETAIL</p>{editing ? <div className="archive-edit"><label htmlFor="edit-title">회의 제목</label><input id="edit-title" value={title} onChange={(e) => setTitle(e.target.value)} /><label htmlFor="edit-note">회의록 내용</label><textarea id="edit-note" value={content} onChange={(e) => setContent(e.target.value)} rows={16} /><div className="archive-edit-actions"><button className="button primary" onClick={() => void save()} disabled={saveState === "saving"}>{saveState === "saving" ? "저장 중..." : "변경사항 저장"}</button><button className="button ghost" onClick={() => setEditing(false)}>취소</button></div>{saveState === "error" && <p className="transcription-error">제목과 회의록 내용을 확인한 뒤 다시 저장해 주세요.</p>}</div> : <><h1>{detail.meeting.title}</h1><p>{new Date(detail.meeting.started_at).toLocaleString("ko-KR")} · {detail.meeting.duration_seconds ? `${Math.round(detail.meeting.duration_seconds / 60)}분` : "진행 중"}</p>{detail.note && <section className="archive-section"><div className="archive-section-heading"><h2>회의록</h2><button className="button ghost small-button" onClick={edit}>수정</button></div><pre>{detail.note.content}</pre></section>}{last && <section className="archive-section"><h2>3줄 요약</h2><p><b>핵심</b> {last.core}</p><p><b>쟁점</b> {last.issues}</p><p><b>발언 참고</b> {last.speaking_point}</p></section>}<section className="archive-section"><h2>한마디 답변</h2>{detail.responses.map((x, i) => <p key={i}>“{x.text}”</p>)}</section><section className="archive-section"><h2>전체 전사</h2>{detail.transcripts.map((x) => <p key={x.sequence}>{x.text}</p>)}</section><div className="archive-actions"><button className="button primary" onClick={edit}>회의 제목·내용 수정</button><button className="button ghost" onClick={() => void remove()}>회의 삭제</button></div></>}</main>;
}
