import { NextResponse } from "next/server";
import { createServerSupabaseClient } from "@/lib/supabase/server";
export const runtime = "nodejs";
type Context = { params: Promise<{ id: string }> };
const timeoutMs = 30000;
const unavailable = () => NextResponse.json({ error: { code: "supabase_not_configured", message: "Supabase 환경변수가 설정되지 않았습니다." } }, { status: 503 });
export async function POST(request: Request, context: Context) {
  const supabase = createServerSupabaseClient(); if (!supabase) return unavailable();
  const { id } = await context.params; const body = await request.json().catch(() => ({})); const question = typeof body.question === "string" ? body.question.trim().slice(0, 2000) : ""; const provider = body.provider === "gemini" || body.provider === "anthropic" ? body.provider : "openai";
  if (!question) return NextResponse.json({ error: { code: "invalid_request", message: "프로젝트에 대한 질문을 입력해 주세요." } }, { status: 400 });
  const [project, contextResult, knowledge, summaries] = await Promise.all([
    supabase.from("projects").select("name,description,default_provider").eq("id", id).single(),
    supabase.from("project_contexts").select("description,objective,background,current_status,key_issues,key_terms,ai_instructions").eq("project_id", id).maybeSingle(),
    supabase.from("project_knowledge").select("id,title,content").eq("project_id", id).eq("archived", false).order("created_at", { ascending: false }).limit(12),
    supabase.from("summaries").select("meeting_id,core,issues,speaking_point,decision,numbers,created_at,meetings(title)").eq("meetings.project_id", id).order("created_at", { ascending: false }).limit(10),
  ]);
  if (project.error || contextResult.error || knowledge.error || summaries.error) return NextResponse.json({ error: { code: "supabase_error", message: "프로젝트 AI 자료를 불러오지 못했습니다." } }, { status: 502 });
  const contextText = JSON.stringify(contextResult.data || {}); const knowledgeText = (knowledge.data || []).map((item) => `[${item.title}]\n${item.content}`).join("\n\n"); const summaryText = (summaries.data || []).map((item) => `[${(item.meetings as unknown as { title?: string } | null)?.title || "지난 회의"}]\n핵심: ${item.core}\n쟁점: ${item.issues}\n결정: ${item.decision || "없음"}`).join("\n\n");
  const prompt = `너는 Meeting Whisper의 프로젝트 AI다. 제공된 프로젝트 Context, Project Knowledge, 과거 회의 Summary에만 근거해 질문에 답하라. 현재 질문이 가장 우선이며, 불확실하거나 정보가 충돌하면 그 사실을 명시하라. 과거 회의의 내용을 현재 결정사항처럼 표현하지 말라. 답변은 간결한 업무용 한국어로 작성하고, 마지막에 근거가 된 회의나 자료를 Sources로 표시하라.\n\n프로젝트: ${project.data?.name || ""}\nProject Context:\n${contextText}\n\nProject Knowledge:\n${knowledgeText || "없음"}\n\n최근 회의 Summary:\n${summaryText || "없음"}\n\n질문:\n${question}`;
  const apiKey = provider === "gemini" ? process.env.GEMINI_API_KEY : provider === "anthropic" ? process.env.ANTHROPIC_API_KEY : process.env.OPENAI_API_KEY; if (!apiKey) return NextResponse.json({ error: { code: "no_api_key", message: "선택한 provider의 서버 API 키가 설정되지 않았습니다." } }, { status: 503 });
  const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), timeoutMs); let answer = "";
  try { let response: Response; if (provider === "openai") { response = await fetch("https://api.openai.com/v1/responses", { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${apiKey}` }, body: JSON.stringify({ model: process.env.OPENAI_SUMMARY_MODEL || "gpt-4o", input: prompt, store: false }), signal: controller.signal }); const payload = await response.json().catch(() => null) as { output_text?: string } | null; answer = payload?.output_text || ""; } else if (provider === "gemini") { response = await fetch("https://generativelanguage.googleapis.com/v1beta/models/gemini-3.7-flash:generateContent", { method: "POST", headers: { "Content-Type": "application/json", "x-goog-api-key": apiKey }, body: JSON.stringify({ contents: [{ parts: [{ text: prompt }] }] }), signal: controller.signal }); const payload = await response.json().catch(() => null) as { candidates?: Array<{ content?: { parts?: Array<{ text?: string }> } }> } | null; answer = payload?.candidates?.[0]?.content?.parts?.map((part) => part.text || "").join("") || ""; } else { response = await fetch("https://api.anthropic.com/v1/messages", { method: "POST", headers: { "content-type": "application/json", "x-api-key": apiKey, "anthropic-version": "2023-06-01" }, body: JSON.stringify({ model: process.env.ANTHROPIC_MODEL || "claude-sonnet-4-20250514", max_tokens: 900, messages: [{ role: "user", content: prompt }] }), signal: controller.signal }); const payload = await response.json().catch(() => null) as { content?: Array<{ text?: string }> } | null; answer = payload?.content?.map((item) => item.text || "").join("") || ""; } if (!response!.ok) return NextResponse.json({ error: { code: "api_error", message: "AI 응답을 생성하지 못했습니다." } }, { status: 502 }); return NextResponse.json({ answer: answer.trim(), sources: (summaries.data || []).map((item) => ({ meeting_id: item.meeting_id, title: (item.meetings as unknown as { title?: string } | null)?.title || "지난 회의" })) }); } catch { return NextResponse.json({ error: { code: "network_error", message: "AI 응답을 생성하지 못했습니다." } }, { status: 504 }); } finally { clearTimeout(timer); }
}
