"use client";
/* eslint-disable @next/next/no-html-link-for-pages */
import { useEffect, useRef, useState } from "react";
import { MAX_AUDIO_UPLOAD_BYTES, ROLLING_BUFFER_LIMIT_MINUTES, ROLLING_BUFFER_LIMIT_SECONDS, useRollingAudioBuffer } from "@/hooks/useRollingAudioBuffer";
import { useRealtimeTranscript } from "@/hooks/useRealtimeTranscript";
import RealtimeTranscript from "@/components/RealtimeTranscript";

type Provider = "openai" | "gemini" | "anthropic";
type Summary = { core: string; issues: string; speakingPoint: string; question: string; decision: string; numbers: string[] };
type Status = "idle" | "analyzing" | "transcribing" | "summarizing" | "generating" | "success" | "error";
const sample: Summary = { core: "내년도 사업은 AI 데이터 확보와 실증을 중심으로 추진하는 방향입니다.", issues: "데이터 확보 비용과 기관 간 데이터 공유 방식이 아직 정리되지 않았습니다.", speakingPoint: "실증사업과 연계해 실제 데이터를 확보하는 방안을 제안하면 좋습니다.", question: "", decision: "", numbers: [] };
const fmt = (n: number) => `${Math.floor(n / 60).toString().padStart(2, "0")}:${(n % 60).toString().padStart(2, "0")}`;
const size = (n: number) => n < 1024 ? `${n} B` : `${(n / 1024).toFixed(1)} KB`;

export default function MeetingDashboard() {
  const audio = useRollingAudioBuffer(); const realtime = useRealtimeTranscript(audio.recording === "recording", audio.recording === "paused");
  const [title, setTitle] = useState(""); const [meetingId, setMeetingId] = useState(""); const [startedAt, setStartedAt] = useState(""); const [saveMessage, setSaveMessage] = useState(""); const [provider, setProvider] = useState<Provider>("openai");
  const [summary, setSummary] = useState<Summary | null>(null); const [summaryStatus, setSummaryStatus] = useState<Status>("idle"); const [summaryError, setSummaryError] = useState(""); const [transcript, setTranscript] = useState(""); const [transcriptStatus, setTranscriptStatus] = useState<Status>("idle"); const [transcriptError, setTranscriptError] = useState(""); const [reply, setReply] = useState(""); const [replyStatus, setReplyStatus] = useState<Status>("idle"); const [replyError, setReplyError] = useState(""); const [emergency, setEmergency] = useState(false); const [whisper, setWhisper] = useState(false); const [step, setStep] = useState(0); const [blobMessage, setBlobMessage] = useState(""); const [note, setNote] = useState(""); const [noteStatus, setNoteStatus] = useState<Status>("idle"); const saved = useRef(new Set<string>());
  const visible = summary || sample; const buffer = Math.min(ROLLING_BUFFER_LIMIT_SECONDS, audio.rollingBuffer.reduce((s, c) => s + c.durationMs, 0)); const bufferSize = audio.rollingBuffer.reduce((s, c) => s + c.blob.size, 0); const recordingLabel = { idle: "대기 중", recording: "녹음 중", paused: "일시정지" }[audio.recording]; const permission = { unknown: "권한 확인 전", requesting: "권한 요청 중", granted: "마이크 사용 가능", denied: "마이크 권한 거부됨", unsupported: "마이크 미지원" }[audio.microphonePermission];
  useEffect(() => { if (!meetingId) return; realtime.segments.forEach((s, i) => { if (!s.isFinal || saved.current.has(s.id)) return; saved.current.add(s.id); void fetch("/api/transcripts", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ meeting_id: meetingId, text: s.text, started_at: new Date(s.timestamp).toISOString(), sequence: i, client_id: s.id }) }).then((r) => { if (!r.ok) { saved.current.delete(s.id); setSaveMessage("전사 저장에 실패했습니다. 녹음은 계속됩니다."); } }); }); }, [meetingId, realtime.segments]);
  const start = async () => { const now = new Date().toISOString(); setStartedAt(now); try { const r = await fetch("/api/meetings", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title: title.trim(), started_at: now }) }); const p = await r.json().catch(() => null); if (!r.ok || !p?.meeting?.id) throw new Error(p?.error?.message || "Supabase에 회의 세션을 저장하지 못했습니다."); setMeetingId(p.meeting.id); setSaveMessage("✓ 회의 세션 저장 완료"); } catch (e) { setSaveMessage(`⚠ ${e instanceof Error ? e.message : "Supabase 연결 실패"} 녹음은 계속됩니다.`); } realtime.start(); void audio.startRecording(); };
  const stop = async () => { const id = meetingId; audio.stopRecording(); if (!id) return; try { const duration = startedAt ? Math.max(0, Math.round((Date.now() - Date.parse(startedAt)) / 1000)) : audio.recordingDuration; const r = await fetch(`/api/meetings/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ended_at: new Date().toISOString(), duration_seconds: duration }) }); if (!r.ok) throw new Error(); setSaveMessage("✓ 회의 종료 및 저장 완료"); } catch { setSaveMessage("⚠ 회의 종료 상태 저장에 실패했습니다."); } };
  const saveSummary = (s: Summary) => { if (meetingId) void fetch("/api/summaries", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ meeting_id: meetingId, summary: s }) }); };
  const summarize = async (text: string) => { setSummaryStatus("summarizing"); setSummaryError(""); setStep(3); try { const r = await fetch("/api/summarize", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ transcript: text, provider }) }); const p = await r.json().catch(() => null); if (!r.ok) throw new Error(p?.error?.message || "AI 요약 요청에 실패했습니다."); const x = p?.summary; if (!x?.core || !x?.issues || !x?.speakingPoint) throw new Error("요약 결과가 올바르지 않습니다."); const s: Summary = { core: x.core, issues: x.issues, speakingPoint: x.speakingPoint, question: x.question || "", decision: x.decision || "", numbers: Array.isArray(x.numbers) ? x.numbers : [] }; setSummary(s); setSummaryStatus("success"); saveSummary(s); setStep(4); setWhisper(true); } catch (e) { setSummaryStatus("error"); setSummaryError(e instanceof Error ? e.message : "AI 요약 요청에 실패했습니다."); } };
  const rescue = async () => { const live = realtime.finalText.trim(); const blob = audio.getRecentRollingBufferAudio(); setEmergency(true); setWhisper(false); setSummary(null); setReply(""); setStep(1); const reliable = realtime.segments.length >= 2 && live.length >= 120; if (reliable) { setTranscript(live); setTranscriptStatus("success"); setBlobMessage(`최근 ${ROLLING_BUFFER_LIMIT_MINUTES}분 확정 전사를 사용합니다.`); await summarize(live); return; } if (!blob) { setTranscriptStatus("error"); setTranscriptError("마이크 데이터가 없습니다. 먼저 녹음을 시작해 주세요."); return; } if (blob.size > MAX_AUDIO_UPLOAD_BYTES) { setTranscriptStatus("error"); setTranscriptError("음성 데이터가 전송 한도를 초과했습니다."); return; } setBlobMessage(`최근 음성 Blob 준비 완료 ${size(blob.size)} · 서버에 자동 업로드하지 않았습니다.`); setTranscriptStatus("transcribing"); setStep(2); const f = new FormData(); f.append("audio", new File([blob], "meeting.webm", { type: blob.type || "audio/webm" })); f.append("provider", provider === "gemini" ? "gemini" : "openai"); try { const r = await fetch("/api/transcribe", { method: "POST", body: f }); const p = await r.json().catch(() => null); if (!r.ok) throw new Error(p?.error?.message || "음성 전사 요청에 실패했습니다."); const text = p?.text?.trim() || ""; setTranscript(text); setTranscriptStatus("success"); if (!text) throw new Error("최근 10분 동안 인식할 수 있는 음성이 없습니다."); await summarize(text); } catch (e) { setTranscriptStatus("error"); setTranscriptError(e instanceof Error ? e.message : "음성 전사 요청에 실패했습니다."); } };
  const replyNow = async () => { if (!transcript || transcript.length < 20 || !summary) { setReplyError("회의 내용이 충분하지 않아 답변을 추천하기 어렵습니다."); return; } setReplyStatus("generating"); try { const r = await fetch("/api/reply", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ provider, transcript, summary }) }); const p = await r.json().catch(() => null); if (!r.ok) throw new Error(p?.error?.message || "답변 생성에 실패했습니다."); const text = p?.reply?.trim() || ""; setReply(text); setReplyStatus("success"); if (meetingId && text) void fetch("/api/responses", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ meeting_id: meetingId, text }) }); } catch (e) { setReplyError(e instanceof Error ? e.message : "답변 생성에 실패했습니다."); } };
  const makeNote = async () => { if (!meetingId) return; setNoteStatus("summarizing"); try { const r = await fetch("/api/meeting-notes", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ meeting_id: meetingId }) }); const p = await r.json().catch(() => null); if (!r.ok) throw new Error(p?.error?.message || "회의록 생성에 실패했습니다."); setNote(p.note?.content || ""); setNoteStatus("success"); } catch (e) { setNoteStatus("error"); setSaveMessage(e instanceof Error ? e.message : "회의록 생성에 실패했습니다."); } };
  const speak = () => { window.speechSynthesis?.cancel(); window.speechSynthesis?.speak(new SpeechSynthesisUtterance(`${visible.speakingPoint}. ${reply}`)); }; const clear = () => { window.speechSynthesis?.cancel(); setEmergency(false); setWhisper(false); setSummary(null); setReply(""); setTranscript(""); setSummaryStatus("idle"); setReplyStatus("idle"); };
  const stage = step === 1 ? `① 최근 ${ROLLING_BUFFER_LIMIT_MINUTES}분 확보` : step === 2 ? "② 대화 내용 파악" : step === 3 ? "③ 핵심만 추리는 중" : step === 4 ? "④ 살려드렸습니다." : "";
  return <main className={`app-shell ${whisper ? "whisper-mode" : ""}`}><header className="topbar"><div className="brand-mark">M</div><div><p className="eyebrow">MEETING WHISPER</p><h1>회의 멍때리기 방지 요약기</h1></div><div className="secure-badge"><span className="lock-dot" /> 브라우저 메모리에만 보관</div></header><section className="hero"><div><p className="hero-kicker">잠깐 딴생각해도 괜찮습니다.</p><h2>지금 무슨 얘기였는지<br /><em>3줄로</em> 알려드립니다.</h2></div><div className="hero-note"><span>✦</span> 직전 {ROLLING_BUFFER_LIMIT_MINUTES}분의 회의 내용을<br />귓속말 컨닝페이퍼로 만들어드려요.</div></section>
    <section className="control-card"><div className="recording-row"><div className={`status-indicator ${audio.recording}`}><span className="status-dot" /><b>{recordingLabel}</b></div><div className="recording-time"><span>현재 녹음 시간</span><strong>{fmt(audio.recordingDuration)}</strong></div></div><div className="permission-row"><span className={`permission-pill ${audio.microphonePermission}`}><span className="permission-dot" /> {permission}</span><small>녹음은 이 브라우저 안에서만 처리됩니다.</small></div><div className="meeting-title-row"><label htmlFor="meeting-title">회의 제목</label><input id="meeting-title" value={title} onChange={(e) => setTitle(e.target.value)} placeholder={`${new Date().toISOString().slice(0, 10)} 회의`} disabled={audio.recording !== "idle"} /></div><div className="provider-row"><label htmlFor="provider">AI provider</label><select id="provider" value={provider} onChange={(e) => setProvider(e.target.value as Provider)}><option value="openai">OpenAI · GPT</option><option value="gemini">Google Gemini</option><option value="anthropic">Claude · Text Summary</option></select></div><div className="controls">{audio.recording === "idle" ? <button className="button primary" onClick={() => void start()}>● 녹음 시작</button> : audio.recording === "paused" ? <button className="button primary" onClick={() => { realtime.start(); audio.resumeRecording(); }}>▶ 녹음 재개</button> : <button className="button pause" onClick={audio.pauseRecording}>Ⅱ 일시정지</button>}<button className="button ghost" onClick={() => void stop()} disabled={audio.recording === "idle"}>■ 녹음 종료</button></div>{audio.error && <p className="error-message">⚠ {audio.error}</p>}<div className="buffer-line"><div className="buffer-copy"><span className="wave-icon">〰</span><span><b>Rolling Buffer</b><small>최근 {ROLLING_BUFFER_LIMIT_MINUTES}분의 음성만 브라우저 메모리에 기억합니다.</small></span></div><div className="buffer-value"><strong>{fmt(buffer)}</strong><span>/ {fmt(ROLLING_BUFFER_LIMIT_SECONDS)}</span></div></div><div className="buffer-track"><span style={{ width: `${Math.min(100, buffer / ROLLING_BUFFER_LIMIT_SECONDS * 100)}%` }} /></div><div className="buffer-meta"><span>● {audio.audioChunks.length}개 chunk 보관 중</span><b>{buffer >= ROLLING_BUFFER_LIMIT_SECONDS ? `최근 ${ROLLING_BUFFER_LIMIT_MINUTES}분 보관 중` : "최근 음성 수집 중"}</b><span>{size(bufferSize)}</span></div>{saveMessage && <p className="save-status" role="status">{saveMessage}</p>}<a className="past-meetings-link" href="/meetings">지난 회의 조회 →</a></section>
    <section className={`summary-card ${emergency ? "emergency" : ""}`}><div className="summary-heading"><div><p className="eyebrow">QUICK RESCUE</p><h2>갑자기 지목됐다면?</h2></div><span className="sparkle">✦</span></div><button className="rescue-button" onClick={() => void rescue()} disabled={transcriptStatus === "transcribing" || summaryStatus === "summarizing"}><span>✦</span> 지금 살려줘!</button><p className="summary-hint">전사 후 선택한 provider가 3줄 컨닝페이퍼를 만듭니다.</p>{stage && <p className="rescue-stage">{stage}</p>}{blobMessage && <p className="blob-message">{blobMessage}</p>}{transcriptError && <p className="transcription-error">{transcriptError}</p>}{summaryError && <p className="transcription-error">{summaryError}</p>}</section>
    <section className="results" aria-live="polite"><div className="results-header"><div><p className="eyebrow">WHISPER NOTES</p><h2>{summaryStatus === "success" ? "지금 바로 이렇게 말해보세요" : "요약 결과"}</h2></div><div className="results-tools"><span className="result-time">{summaryStatus === "success" ? "AI 요약 결과" : "예시 데이터"}</span>{summaryStatus === "success" && <button className="whisper-toggle" onClick={() => setWhisper(true)}>귓속말 모드</button>}</div></div><div className="result-grid"><article className="result-item"><span className="number">01</span><div><h3>지금 논의한 핵심</h3><p>{visible.core}</p></div></article><article className="result-item"><span className="number">02</span><div><h3>주요 쟁점</h3><p>{visible.issues}</p></div></article><article className="result-item highlight"><span className="number">03</span><div><h3>내가 말할 때 참고할 포인트</h3><p>{visible.speakingPoint}</p></div></article></div>{summaryStatus === "success" && <div className="reply-panel"><button className="button reply-button" onClick={() => void replyNow()}>✦ 한마디 만들어줘</button>{reply && <p className="reply-text">“{reply}”</p>}{replyError && <p className="transcription-error">{replyError}</p>}</div>}{(summaryStatus === "success" || transcript) && <div className="result-actions"><button className="button primary" onClick={() => void summarize(transcript)}>↻ 다시 요약</button>{reply && <button className="button ghost" onClick={speak}>🔊 귓속말로 읽어줘</button>}<button className="button ghost" onClick={clear}>× 결과 지우기</button></div>}</section>
    <section className="whisper-panel"><div className="whisper-top"><span className="eyebrow">WHISPER MODE</span><button className="whisper-exit" onClick={() => setWhisper(false)}>일반 화면</button></div><p className="whisper-question">[OO님 의견은요?]</p><div className="whisper-lines"><div><span>① 무슨 얘기?</span><strong>{visible.core}</strong></div><div><span>② 뭐가 쟁점?</span><strong>{visible.issues}</strong></div><div><span>③ 나는 뭐라고 하지?</span><strong>{reply || visible.speakingPoint}</strong></div></div><div className="whisper-actions"><button className="button reply-button" onClick={() => void replyNow()}>✦ 한마디 만들어줘</button>{reply && <button className="button ghost" onClick={speak}>🔊 귓속말로 읽어줘</button>}</div></section>
    <RealtimeTranscript segments={realtime.segments} interimTranscript={realtime.interimTranscript} status={realtime.status} error={realtime.error} />{audio.recording === "idle" && meetingId && <section className="meeting-finished"><p className="eyebrow">MEETING SAVED</p><h2>회의가 종료되었습니다.</h2><button className="button primary" onClick={() => void makeNote()} disabled={noteStatus === "summarizing"}>📝 회의록 만들기</button>{note && <pre className="meeting-note">{note}</pre>}</section>}<footer><span>●</span> 음성 데이터는 서버에 자동 업로드되지 않으며, 녹음 종료 시 브라우저 메모리에서 삭제됩니다.</footer></main>;
}
