"use client";
/* eslint-disable react-hooks/set-state-in-effect, react-hooks/static-components, react/no-unescaped-entities */

import { useEffect, useMemo, useRef, useState } from "react";
import { MAX_AUDIO_UPLOAD_BYTES, ROLLING_BUFFER_LIMIT_MINUTES, useRollingAudioBuffer } from "@/hooks/useRollingAudioBuffer";
import { useRealtimeTranscript } from "@/hooks/useRealtimeTranscript";
import RealtimeTranscript from "@/components/RealtimeTranscript";

type Provider = "openai" | "gemini" | "anthropic";
type Summary = { core: string; issues: string; speakingPoint: string; question: string; decision: string; numbers: string[] };
type Status = "idle" | "analyzing" | "transcribing" | "summarizing" | "generating" | "success" | "error";
type Theme = "system" | "light" | "dark";
type Meeting = { id: string; title: string; started_at: string; duration_seconds: number | null; status: string };

const providerInfo: Record<Provider, { name: string; mark: string }> = { openai: { name: "OpenAI", mark: "O" }, gemini: { name: "Gemini", mark: "G" }, anthropic: { name: "Claude", mark: "C" } };
const formatTime = (seconds: number) => `${Math.floor(seconds / 60).toString().padStart(2, "0")}:${(seconds % 60).toString().padStart(2, "0")}`;
const formatMeetingDate = (value: string) => new Date(value).toLocaleDateString("ko-KR", { month: "short", day: "numeric" });
const formatBytes = (bytes: number) => bytes < 1024 ? `${bytes} B` : `${(bytes / 1024).toFixed(1)} KB`;

function ProviderMark({ provider }: { provider: Provider }) { return <span className={`provider-mark provider-${provider}`}>{providerInfo[provider].mark}</span>; }

export default function MeetingDashboard() {
  const audio = useRollingAudioBuffer();
  const realtime = useRealtimeTranscript(audio.recording === "recording", audio.recording === "paused");
  const [meetings, setMeetings] = useState<Meeting[]>([]);
  const [meetingTitle, setMeetingTitle] = useState("");
  const [meetingId, setMeetingId] = useState("");
  const [startedAt, setStartedAt] = useState("");
  const [provider, setProvider] = useState<Provider>("openai");
  const [providerOpen, setProviderOpen] = useState(false);
  const [sidebarOpen, setSidebarOpen] = useState(true);
  const [mobileSidebarOpen, setMobileSidebarOpen] = useState(false);
  const [settingsOpen, setSettingsOpen] = useState(false);
  const [searchOpen, setSearchOpen] = useState(false);
  const [search, setSearch] = useState("");
  const [theme, setTheme] = useState<Theme>("system");
  const [summary, setSummary] = useState<Summary | null>(null);
  const [summaryStatus, setSummaryStatus] = useState<Status>("idle");
  const [summaryError, setSummaryError] = useState("");
  const [transcriptText, setTranscriptText] = useState("");
  const [transcriptionStatus, setTranscriptionStatus] = useState<Status>("idle");
  const [transcriptionError, setTranscriptionError] = useState("");
  const [reply, setReply] = useState("");
  const [replyStatus, setReplyStatus] = useState<Status>("idle");
  const [replyError, setReplyError] = useState("");
  const [saveMessage, setSaveMessage] = useState("");
  const [whisperMode, setWhisperMode] = useState(false);
  const [rescueStep, setRescueStep] = useState("");
  const savedTranscriptIds = useRef(new Set<string>());

  const loadMeetings = async (query = "") => { try { const response = await fetch(`/api/meetings${query ? `?q=${encodeURIComponent(query)}` : ""}`); const payload = await response.json().catch(() => null); if (response.ok) setMeetings(payload?.meetings || []); } catch { /* recording must remain available if archive is unavailable */ } };
  useEffect(() => { void loadMeetings(); const stored = window.localStorage.getItem("meeting-whisper-theme") as Theme | null; if (stored === "system" || stored === "light" || stored === "dark") setTheme(stored); }, []);
  useEffect(() => { const root = document.documentElement; root.dataset.theme = theme; window.localStorage.setItem("meeting-whisper-theme", theme); }, [theme]);
  useEffect(() => { const close = (event: KeyboardEvent) => { if (event.key === "Escape") { setSettingsOpen(false); setProviderOpen(false); setMobileSidebarOpen(false); } }; window.addEventListener("keydown", close); return () => window.removeEventListener("keydown", close); }, []);
  useEffect(() => { if (!meetingId) return; realtime.segments.forEach((segment, index) => { if (!segment.isFinal || savedTranscriptIds.current.has(segment.id)) return; savedTranscriptIds.current.add(segment.id); void fetch("/api/transcripts", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ meeting_id: meetingId, text: segment.text, started_at: new Date(segment.timestamp).toISOString(), sequence: index, client_id: segment.id }) }).then((response) => { if (!response.ok) { savedTranscriptIds.current.delete(segment.id); setSaveMessage("전사 저장에 실패했습니다. 녹음은 계속됩니다."); } }); }); }, [meetingId, realtime.segments]);

  const groupedMeetings = useMemo(() => { const groups = new Map<string, Meeting[]>(); meetings.forEach((meeting) => { const key = new Date(meeting.started_at).toDateString(); groups.set(key, [...(groups.get(key) || []), meeting]); }); return [...groups.entries()].map(([key, items]) => ({ label: key === new Date().toDateString() ? "오늘" : "이전 회의", items })); }, [meetings]);
  const selectedProvider = providerInfo[provider];
  const recordingLabel = audio.recording === "recording" ? "Recording" : audio.recording === "paused" ? "Paused" : "Ready";
  const liveText = realtime.finalText.trim();
  const bufferDuration = audio.rollingBuffer.reduce((total, chunk) => total + chunk.durationMs, 0);

  const startMeeting = async () => { const now = new Date().toISOString(); setStartedAt(now); setSaveMessage(""); try { const response = await fetch("/api/meetings", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title: meetingTitle.trim(), started_at: now }) }); const payload = await response.json().catch(() => null); if (!response.ok || !payload?.meeting?.id) throw new Error(payload?.error?.message || "회의 세션을 저장하지 못했습니다."); setMeetingId(payload.meeting.id); setMeetings((current) => [payload.meeting, ...current]); } catch (error) { setSaveMessage(error instanceof Error ? `${error.message} 녹음은 계속됩니다.` : "저장에 실패했지만 녹음은 계속됩니다."); } realtime.start(); await audio.startRecording(); setMobileSidebarOpen(false); };
  const stopMeeting = async () => { const id = meetingId; audio.stopRecording(); if (!id) return; const duration = startedAt ? Math.max(0, Math.round((Date.now() - Date.parse(startedAt)) / 1000)) : audio.recordingDuration; try { const response = await fetch(`/api/meetings/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ended_at: new Date().toISOString(), duration_seconds: duration }) }); if (!response.ok) throw new Error(); setSaveMessage("회의가 저장되었습니다."); void loadMeetings(); } catch { setSaveMessage("회의 종료 상태를 저장하지 못했습니다."); } };
  const saveSummary = (result: Summary) => { if (meetingId) void fetch("/api/summaries", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ meeting_id: meetingId, summary: result }) }); };
  const summarize = async (text: string) => { setSummaryStatus("summarizing"); setSummaryError(""); setRescueStep("Understanding"); try { const response = await fetch("/api/summarize", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ transcript: text, provider }) }); const payload = await response.json().catch(() => null); if (!response.ok) throw new Error(payload?.error?.message || "AI Brief를 만들지 못했습니다."); const raw = payload?.summary; if (!raw?.core || !raw?.issues || !raw?.speakingPoint) throw new Error("AI Brief 결과가 올바르지 않습니다."); const result: Summary = { core: raw.core, issues: raw.issues, speakingPoint: raw.speakingPoint, question: raw.question || "", decision: raw.decision || "", numbers: Array.isArray(raw.numbers) ? raw.numbers : [] }; setSummary(result); setSummaryStatus("success"); saveSummary(result); setRescueStep("Briefing"); setWhisperMode(true); } catch (error) { setSummaryStatus("error"); setSummaryError(error instanceof Error ? error.message : "AI Brief를 만들지 못했습니다."); setRescueStep(""); } };
  const catchUp = async () => { setWhisperMode(false); setReply(""); setSummary(null); setSummaryError(""); setTranscriptionError(""); setRescueStep("Listening"); const recentLive = realtime.finalText.trim(); const hasReliableLive = realtime.segments.length >= 2 && recentLive.length >= 120; const audioBlob = audio.getRecentRollingBufferAudio(); if (hasReliableLive) { setTranscriptText(recentLive); setTranscriptionStatus("success"); await summarize(recentLive); return; } if (!audioBlob) { setTranscriptionError("최근 회의 음성이 없습니다. 먼저 회의를 시작해 주세요."); setRescueStep(""); return; } if (audioBlob.size > MAX_AUDIO_UPLOAD_BYTES) { setTranscriptionError("최근 음성 데이터가 전송 한도를 초과했습니다."); setRescueStep(""); return; } setTranscriptionStatus("transcribing"); setRescueStep("Understanding"); const form = new FormData(); form.append("audio", new File([audioBlob], "meeting.webm", { type: audioBlob.type || "audio/webm" })); form.append("provider", provider === "gemini" ? "gemini" : "openai"); try { const response = await fetch("/api/transcribe", { method: "POST", body: form }); const payload = await response.json().catch(() => null); if (!response.ok) throw new Error(payload?.error?.message || "음성을 전사하지 못했습니다."); const text = payload?.text?.trim() || ""; if (!text) throw new Error("최근 회의에서 인식할 수 있는 음성이 없습니다."); setTranscriptText(text); setTranscriptionStatus("success"); await summarize(text); } catch (error) { setTranscriptionError(error instanceof Error ? error.message : "음성을 전사하지 못했습니다."); setRescueStep(""); } };
  const generateReply = async () => { if (!summary || transcriptText.length < 20) { setReplyError("회의 내용이 충분하지 않아 추천 답변을 만들기 어렵습니다."); return; } setReplyStatus("generating"); setReplyError(""); try { const response = await fetch("/api/reply", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ provider, transcript: transcriptText, summary }) }); const payload = await response.json().catch(() => null); if (!response.ok) throw new Error(payload?.error?.message || "추천 답변을 만들지 못했습니다."); const text = payload?.reply?.trim() || ""; setReply(text); setReplyStatus("success"); if (meetingId && text) void fetch("/api/responses", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ meeting_id: meetingId, text }) }); } catch (error) { setReplyStatus("error"); setReplyError(error instanceof Error ? error.message : "추천 답변을 만들지 못했습니다."); } };
  const speak = () => { if (!window.speechSynthesis) { setReplyError("이 브라우저에서는 음성 읽기를 지원하지 않습니다."); return; } window.speechSynthesis.cancel(); window.speechSynthesis.speak(new SpeechSynthesisUtterance(`${summary?.speakingPoint || ""}. ${reply}`)); };
  const copyReply = async () => { if (reply) await navigator.clipboard?.writeText(reply); };
  const chooseProvider = (next: Provider) => { setProvider(next); setProviderOpen(false); };

  const Sidebar = () => <aside className={`app-sidebar ${sidebarOpen ? "expanded" : "collapsed"} ${mobileSidebarOpen ? "mobile-open" : ""}`}><div className="sidebar-brand"><span className="brand-wordmark">Meeting Whisper</span><button className="sidebar-collapse" aria-label="사이드바 접기" onClick={() => setSidebarOpen((open) => !open)}>{sidebarOpen ? "‹" : "›"}</button></div><button className="new-meeting-button" onClick={() => { setMeetingId(""); setMeetingTitle(""); setSummary(null); setTranscriptText(""); setMobileSidebarOpen(false); }}><span>+</span><span>새 회의</span></button>{sidebarOpen && <><div className="sidebar-section-header"><span>회의</span><button aria-label="회의 검색" onClick={() => setSearchOpen((open) => !open)}>⌕</button></div>{searchOpen && <div className="sidebar-search"><input autoFocus value={search} onChange={(event) => setSearch(event.target.value)} placeholder="회의 검색" onKeyDown={(event) => { if (event.key === "Enter") void loadMeetings(search); }} /></div>}<div className="sidebar-meetings">{groupedMeetings.map((group) => <div className="meeting-group" key={group.label}><span className="meeting-group-label">{group.label}</span>{group.items.map((meeting) => <a className={`sidebar-meeting ${meeting.id === meetingId ? "active" : ""}`} href={`/meetings/${meeting.id}`} key={meeting.id}><span className="sidebar-meeting-title">{meeting.title}</span><span>{formatMeetingDate(meeting.started_at)}</span></a>)}</div>)}{!meetings.length && <p className="sidebar-empty">아직 저장된 회의가 없습니다.</p>}</div></>}<div className="sidebar-bottom"><button className="settings-button" onClick={() => setSettingsOpen((open) => !open)}><span className="settings-glyph">⚙</span><span>설정</span></button>{settingsOpen && <div className="settings-popover" role="dialog" aria-label="설정"><strong>설정</strong><span className="settings-label">화면 모드</span><div className="theme-options">{(["system", "light", "dark"] as Theme[]).map((option) => <button className={theme === option ? "selected" : ""} key={option} onClick={() => setTheme(option)}>{theme === option ? "✓" : "○"} {option === "system" ? "시스템 설정" : option === "light" ? "라이트 모드" : "다크 모드"}</button>)}</div><span className="settings-label">AI Provider</span><div className="settings-provider">{(Object.keys(providerInfo) as Provider[]).map((option) => <button key={option} onClick={() => chooseProvider(option)}><ProviderMark provider={option} /> {providerInfo[option].name}</button>)}</div></div>}</div></aside>;

  return <div className={`meeting-app ${whisperMode ? "focus-mode" : ""}`}><Sidebar />{mobileSidebarOpen && <button className="mobile-overlay" aria-label="메뉴 닫기" onClick={() => setMobileSidebarOpen(false)} />}<main className="workspace"><header className="workspace-header"><div className="mobile-header-left"><button className="mobile-menu-button" aria-label="사이드바 열기" onClick={() => setMobileSidebarOpen(true)}>☰</button><div><span className="workspace-kicker">{audio.recording === "idle" ? "Workspace" : "Live meeting"}</span><h1>{meetingTitle || "새 회의"}</h1></div></div><div className="workspace-header-actions"><div className="provider-selector"><button className="provider-trigger" onClick={() => setProviderOpen((open) => !open)}><ProviderMark provider={provider} /> {selectedProvider.name}<span className="chevron">⌄</span></button>{providerOpen && <div className="provider-popover" role="menu"><span>AI Provider</span>{(Object.keys(providerInfo) as Provider[]).map((option) => <button role="menuitem" className={provider === option ? "selected" : ""} key={option} onClick={() => chooseProvider(option)}><ProviderMark provider={option} />{providerInfo[option].name}{provider === option && <b>✓</b>}</button>)}</div>}</div>{audio.recording !== "idle" && <button className="end-meeting-button" onClick={() => void stopMeeting()}>회의 종료</button>}</div></header><section className="workspace-body">
    {audio.recording === "idle" && !meetingId ? <section className="new-meeting-view"><span className="section-eyebrow">NEW MEETING</span><h2>새 회의를 시작하세요.</h2><p>실시간 전사와 AI Brief를 준비합니다.</p><label htmlFor="new-meeting-title">회의 제목</label><input id="new-meeting-title" value={meetingTitle} onChange={(event) => setMeetingTitle(event.target.value)} placeholder="예: 2026 AI 사업 추진회의" /><div className="new-meeting-provider"><span>AI Provider</span><button className="inline-provider" onClick={() => setProviderOpen((open) => !open)}><ProviderMark provider={provider} /> {selectedProvider.name} ⌄</button></div><button className="start-meeting-button" onClick={() => void startMeeting()}>회의 시작</button></section> : <><section className="meeting-status-bar"><div><span className={`recording-indicator ${audio.recording}`} /><span>{recordingLabel}</span><strong>{formatTime(audio.recordingDuration)}</strong><small>{bufferDuration > 0 ? `최근 ${ROLLING_BUFFER_LIMIT_MINUTES}분 보관 중` : ""}</small></div><div className="meeting-save-status">{saveMessage}</div></section><div className="meeting-grid"><section className="transcript-workspace"><div className="panel-heading"><div><span className="section-eyebrow">LIVE TRANSCRIPT</span><h2>실시간 전사</h2></div><span className="panel-caption">최근 대화</span></div><RealtimeTranscript segments={realtime.segments} interimTranscript={realtime.interimTranscript} status={realtime.status} error={realtime.error} /></section><aside className="brief-workspace"><div className="brief-header"><div><span className="section-eyebrow">AI BRIEF</span><h2>{summary ? "회의를 따라잡았습니다." : "현재 회의"}</h2></div>{summary && <button className="whisper-mode-button" onClick={() => setWhisperMode(true)}>Whisper Mode</button>}</div>{summary ? <div className="brief-content"><div className="brief-row"><span>핵심</span><p>{summary.core}</p></div><div className="brief-row"><span>쟁점</span><p>{summary.issues}</p></div><div className="brief-row accent-row"><span>발언 포인트</span><p>{summary.speakingPoint}</p></div><div className="brief-actions"><button onClick={() => void generateReply()} disabled={replyStatus === "generating"}>{replyStatus === "generating" ? "추천 답변 생성 중..." : "Suggested response"}</button>{reply && <><button onClick={() => void copyReply()}>Copy</button><button onClick={speak}>Speak</button></>}</div>{reply && <p className="suggested-response">{reply}</p>}{replyError && <p className="inline-error">{replyError}</p>}</div> : <div className="brief-empty"><p>Catch me up을 누르면<br />최근 대화의 핵심을 정리합니다.</p></div>}</aside></div><div className="workspace-bottom"><button className="catch-up-button" onClick={() => void catchUp()} disabled={transcriptionStatus === "transcribing" || summaryStatus === "summarizing"}>{rescueStep ? `${rescueStep}...` : "지금 따라잡기"}<small>직전 대화를 빠르게 정리합니다.</small></button>{(transcriptionError || summaryError) && <p className="inline-error">{transcriptionError || summaryError}</p>}</div></>}
    </section></main>{whisperMode && summary && <section className="whisper-overlay"><div className="whisper-focus-card"><div className="whisper-focus-header"><span>WHISPER MODE</span><button onClick={() => setWhisperMode(false)}>닫기</button></div><div className="whisper-focus-row"><span>WHAT'S HAPPENING</span><strong>{summary.core}</strong></div><div className="whisper-focus-row"><span>WHAT'S THE ISSUE</span><strong>{summary.issues}</strong></div><div className="whisper-focus-row focus-answer"><span>WHAT SHOULD I SAY?</span><strong>{reply || summary.speakingPoint}</strong></div><button className="focus-speak-button" onClick={speak}>Speak</button></div></section>}</div>;
}
