"use client";
/* eslint-disable react-hooks/set-state-in-effect, react-hooks/exhaustive-deps */
import { useEffect, useState } from "react";

type Project = { id: string; name: string; description?: string | null };
type Context = { description: string; objective: string; background: string; current_status: string; key_issues: string; key_terms: string; ai_instructions: string };
type Knowledge = { id: string; title: string; content: string; created_at: string };
const emptyContext: Context = { description: "", objective: "", background: "", current_status: "", key_issues: "", key_terms: "", ai_instructions: "" };
export default function ProjectWorkspace({ id }: { id: string }) {
  const [project, setProject] = useState<Project | null>(null); const [context, setContext] = useState<Context>(emptyContext); const [knowledge, setKnowledge] = useState<Knowledge[]>([]); const [tab, setTab] = useState("Overview"); const [editing, setEditing] = useState(false); const [title, setTitle] = useState(""); const [content, setContent] = useState(""); const [question, setQuestion] = useState(""); const [answer, setAnswer] = useState(""); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  const load = async () => { const [p, c, k] = await Promise.all([fetch("/api/projects").then((r) => r.json()), fetch(`/api/projects/${id}/context`).then((r) => r.json()), fetch(`/api/projects/${id}/knowledge`).then((r) => r.json())]); setProject((p.projects || []).find((item: Project) => item.id === id) || null); setContext({ ...emptyContext, ...(c.context || {}) }); setKnowledge(k.knowledge || []); };
  useEffect(() => { void load(); }, [id]);
  const saveContext = async () => { setBusy(true); const response = await fetch(`/api/projects/${id}/context`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(context) }); setBusy(false); if (response.ok) { setEditing(false); setMessage("프로젝트 정보를 저장했습니다."); } else setMessage("프로젝트 정보를 저장하지 못했습니다."); };
  const addKnowledge = async () => { if (!title.trim() || !content.trim()) return; setBusy(true); const response = await fetch(`/api/projects/${id}/knowledge`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title, content }) }); const payload = await response.json(); setBusy(false); if (response.ok) { setKnowledge((items) => [payload.knowledge, ...items]); setTitle(""); setContent(""); setMessage("프로젝트 지식을 저장했습니다."); } };
  const ask = async () => { if (!question.trim()) return; setBusy(true); const response = await fetch(`/api/projects/${id}/ask`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ question }) }); const payload = await response.json(); setBusy(false); setAnswer(response.ok ? payload.answer : payload.error?.message || "AI 응답을 생성하지 못했습니다."); };
  if (!project) return <section className="project-workspace"><p>프로젝트를 불러오는 중...</p></section>;
  return <section className="project-workspace"><header className="project-heading"><div><span className="section-eyebrow">PROJECT</span><h2>{project.name}</h2><p>{project.description || "프로젝트 Context와 회의 지식을 관리합니다."}</p></div><button className="button primary" onClick={() => setEditing(true)}>프로젝트 정보 편집</button></header><nav className="project-tabs">{["Overview", "Meetings", "Knowledge", "Settings"].map((item) => <button className={tab === item ? "active" : ""} key={item} onClick={() => setTab(item)}>{item}</button>)}</nav>{tab === "Overview" && <><div className="project-context-grid">{([["목표", "objective"], ["배경", "background"], ["현재 상황", "current_status"], ["핵심 쟁점", "key_issues"], ["주요 용어", "key_terms"], ["AI 지침", "ai_instructions"]] as [string, keyof Context][]).map(([label, key]) => <div key={key}><span>{label}</span><p>{context[key] || "아직 입력되지 않았습니다."}</p></div>)}</div><div className="project-ai"><span className="section-eyebrow">PROJECT AI</span><h3>이 프로젝트에 대해 AI에게 질문하세요.</h3><div className="project-ai-form"><input value={question} onChange={(event) => setQuestion(event.target.value)} placeholder="예: 지난 회의에서 결정된 사항은?" /><button className="button primary" onClick={() => void ask()} disabled={busy}>질문</button></div>{answer && <div className="project-ai-answer"><p>{answer}</p></div>}</div></>}{tab === "Knowledge" && <div className="project-knowledge"><div className="project-knowledge-heading"><div><span className="section-eyebrow">PROJECT KNOWLEDGE</span><h3>프로젝트 지식</h3></div></div><div className="knowledge-form"><input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="지식 제목" /><textarea value={content} onChange={(event) => setContent(event.target.value)} placeholder="프로젝트에서 계속 참고할 내용을 입력하세요." rows={5} /><button className="button primary" onClick={() => void addKnowledge()} disabled={busy}>지식 저장</button></div>{knowledge.map((item) => <article className="knowledge-item" key={item.id}><strong>{item.title}</strong><small>{new Date(item.created_at).toLocaleDateString("ko-KR")}</small><p>{item.content}</p></article>)}</div>}{editing && <div className="project-context-editor"><h3>프로젝트 정보</h3>{([['description','프로젝트 설명'],['objective','목표'],['background','배경'],['current_status','현재 상황'],['key_issues','핵심 쟁점'],['key_terms','주요 용어'],['ai_instructions','AI 지침']] as [keyof Context,string][]).map(([key,label]) => <label key={key}>{label}<textarea rows={3} value={context[key]} onChange={(event) => setContext((current) => ({ ...current, [key]: event.target.value }))} /></label>)}<div className="detail-actions"><button className="button primary" onClick={() => void saveContext()} disabled={busy}>저장</button><button className="button" onClick={() => setEditing(false)}>취소</button></div></div>}{message && <p className="workspace-action-message">{message}</p>}</section>;
}
